export enum Type {
  MEAT = 'MEAT',
  FISH = 'FISH',
  FRUIT = 'FRUIT',
  VEGETABLE = 'VEGETABLE',
  DAIRY = 'DAIRY',
  EGG  = 'EGG',
  BEVERAGE = 'BEVERAGE',
  SPICE = 'SPICE',
  NUTS = 'NUTS',
  OILS = 'OILS',
  MUSHROOMS = 'MUSHROOMS',
  SWEETS  = 'SWEETS',
  HONEY = 'HONEY',
  HERBS = 'HERBS',
  GRAIN_PRODUCTS = 'GRAIN_PRODUCTS',
  VEGAN_PRODUCTS = 'VEGAN_PRODUCTS',
  OTHER = 'OTHER'
}
